spring:
  data:
    mongodb:
      username: saikumar
      password: saikumar
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
      
    
server:
  port: 8090
      
